//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalAccounting
    {
        public int ID { get; set; }
        public int Instruction_FK { get; set; }
        public int Employer_FK { get; set; }
    
        public virtual Instruction Instruction { get; set; }
        public virtual Users Users { get; set; }
    }
}
